
# 6. Библиотеки для получения и обработки данных

## 6.1. Модули math и numpy

### Теория

#### Библиотека math

In [1]:
import math

##### Функции теории чисел и функции представления

`math.comb(n, k)` – возвращает количество сочетаний из n элементов по k элементам без повторений и без учёта порядка. Cколькими **способами** можно выбрать 3 объекта из множества в 12 объектов (порядок не важен):

In [6]:
print(math.comb(12, 3))  # 220

220


`math.factorial(x)` – возвращает факториал целого неотрицательного числа x:

In [3]:
print(math.factorial(5))  # 120

120


`math.gcd(*integers)` – возвращает наибольший общий делитель (НОД) для чисел-аргументов

In [4]:
print(math.gcd(120, 210, 360))  # 30

30


`math.lcm(*integers)` – возвращает наименьшее общее кратное (НОК) для чисел-аргументов

In [5]:
print(math.lcm(10, 20, 30, 40))  # 120

120


`math.perm(n, k=None)` – возвращает количество **размещений** из n элементов по k элементам без повторений и с учётом порядка. Если значение аргумента k не задано, то возвращается количество перестановок множества из n элементов:

In [6]:
print(math.perm(4, 2))  # 12
print(math.perm(4))  # 24

12
24


`math.prod(iterable, start=1)` – возвращает произведение элементов итерируемого объекта iterable. Если iterable пустой, то возвращается значение именованного аргумента start:

In [8]:
print(math.prod(range(10, 21)))  # 6704425728000

6704425728000


##### Степенные и логарифмические функции

`math.exp(x)` – возвращает значение экспоненциальной функции e^x:

In [8]:
print(math.exp(3.5))  # 33.11545195869231

33.11545195869231


`math.log(x, base)` – возвращает значение логарифма от x по основанию base. Если значение аргумента base не задано, то вычисляется натуральный логарифм. Вычисление производится по формуле log(x) / log(base):

In [9]:
print(math.log(10))  # 2.302585092994046
print(math.log(10, 2))  # 3.3219280948873626

2.302585092994046
3.3219280948873626


`math.pow(x, y)` – возвращает значение x в степени y. В отличие от операции ** происходит преобразование обоих аргументов в вещественные числа:

In [10]:
print(math.pow(2, 10))  # 1024.0
print(math.pow(4.5, 3.7))  # 261.1477575641718

1024.0
261.1477575641718


In [11]:
print(2**10)
print(4.5**3.7)

1024
261.1477575641718


##### Тригонометрические функции

Доступны функции синус (sin(x)), косинус (cos(x)), тангенс (tan(x)), арксинус (asin(x)), арккосинус (acos(x)), арктангенс (atan(x)). **Угол задаётся и возвращается в радианах**.

Имеются особенные функции:

`math.dist(p, q)` – возвращает Евклидово расстояние между точками p и q, заданными как итерируемые объекты одной длины:

In [3]:
print(math.dist((0, 0, 0), (1, 1, 1)))  # 1.7320508075688772

1.7320508075688772


`math.hypot(*coordinates)` – возвращает длину многомерного вектора с координатами, заданными в позиционных аргументах coordinates, и началом в центре системы координат. Для двумерной системы координат функция возвращает длину гипотенузы прямоугольного треугольника по теореме Пифагора:

In [4]:
print(math.hypot(1, 1, 1))  # 1.7320508075688772
print(math.hypot(3, 4))  # 5.0

1.7320508075688772
5.0


##### Функции преобразования угла

`math.degrees(x)` – преобразует угол из радиан в градусы:

In [5]:
print(round(math.sin(math.radians(30)), 1))  # 0.5

0.5


`math.radians(x)` – преобразует угол из градусов в радианы

In [6]:
print(round(math.degrees(math.asin(0.5)), 1))  # 30.0

30.0


##### Гиперболические функции

Доступны функции acosh(x), asinh(x), atanh(x), cosh(x), sinh(x), tanh(x)

##### Специальные функции

Среди специальных функций интерес представляет Гамма-функция. Она описывает гладкую непрерывную функцию f(x) = (x - 1)!, график которой проходит через точки, соответствующие значениям функции факториала для целых чисел. Другими словами, Гамма-функция интерполирует значения факториала для вещественных чисел:

In [7]:
print(math.gamma(3))  # 2.0
print(math.gamma(3.5))  # 3.323350970447842
print(math.gamma(4))  # 6.0

2.0
3.323350970447842
6.0


##### Константы

In [8]:
math.pi

3.141592653589793

In [9]:
math.e

2.718281828459045

#### Библиотека numpy

Numpy (Numerical Python, читается как "нампАй") - нестандартная библиотека. Установить можно из репозитория PyPI (Python Package Index).

In [13]:
import numpy as np

##### np.array()

In [14]:
# vibo: создание массива из списка с помощью функции array()
a = np.array([1, 2, 3, 4])
b = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
# vibo: индексация
print(f"a[0] = {a[0]}")
print(f"b[0] = {b[0]}")

a[0] = 1
b[0] = [1 2]


In [18]:
# vibo: количество осей (axis по документации)
print(a.ndim) # 1
print(b.ndim) # 2

1
2


In [21]:
# vibo: массив a имеет одну ось длинной 4 элемента
print(a.shape) # 4
# vibo: имеет две оси, длина первой оси 4, второй 2
print(b.shape) # 4, 2

(4,)
(4, 2)


Массивы numpy являются объектами класса ndarray. Наиболее важными атрибутами класса ndarray:

- `ndarray.ndim` – размерность (количество осей) массива;
- `ndarray.shape` – кортеж, значения которого содержат количество элементов по каждой из осей массива;
- `ndarray.size` – общее количество элементов массива;
- `ndarray.dtype` – объект, описывающий тип данных элементов массива;
- `ndarray.itemsize` – размер памяти в байтах, занимаемый одним элементом массива.

In [30]:
from numpy import int32

# vibo: без явного указания типа, данные приводились к int64
# a = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
a = np.array([[1, 2], [3, 4], [5, 6], [7, 8]], dtype=int32)
print(f"a.ndim = {a.ndim}, a.shape = {a.shape}, a.size = {a.size}, a.dtype = {a.dtype}")

a.ndim = 2, a.shape = (4, 2), a.size = 8, a.dtype = int32


**`int32` целые числа со знаком (отрицательные и положительные) и размером занимаемой памяти 32 бита, диапазон от -2 147 483 648 до 2 147 483 647**

**`uint8` целые числа без знака размером 8 бит, диапазон значений от 0 до 255**

In [28]:
a = np.array([1, 2, 3], dtype="uint8")
# vibo: хотим поменять первый элемент на значение не из диапазона 0 - 255
a[0] = 256
# vibo: значение элемента не вышло за пределы диапазона, а было взято с его начала
print(a) # 0 2 3

[0 2 3]


Типы данных numpy https://numpy.org/doc/stable/user/basics.types.html

In [32]:
a = np.array([1, 2.5, 3])
print(a)
print(a.dtype)
b = np.array(['text', 1, 2.5])
print(b)
# vibo: <U32 - Unicode длиной 32 символа
print(b.dtype)

[1.  2.5 3. ]
float64
['text' '1' '2.5']
<U32


In [33]:
# vibo: создание массива из нулей
a = np.zeros((4, 3))
print(a)
print()
a = np.zeros((4, 3), dtype="int32")
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [34]:
# vibo: создание массива из единиц
a = np.ones((4, 3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


##### np.arange()

In [35]:
# vibo: создания массива, заполненного значениями из диапазона
# vibo: начало, конец (не включая)
a = np.arange(1, 10)
print(a)
print()
# vibo: начало, конец (не включая), шаг
a = np.arange(1, 5, 0.4)
print(a)

[1 2 3 4 5 6 7 8 9]

[1.  1.4 1.8 2.2 2.6 3.  3.4 3.8 4.2 4.6]


In [36]:
# vibo: начало, конец (включая), количество значений
a = np.linspace(1, 5, 10)  # задаётся начало, конец диапазона и количество значений
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


##### reshape()

In [37]:
# vibo: изменение размерности
a = np.zeros((4, 3), dtype="uint8")
print(a)
print()
a = a.reshape((2, 6))
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [72]:
# vibo: свой пример
my_a = np.arange(1, 65, 1)
print(my_a)
print()
# vibo: через reshape()
my_a1 = my_a.reshape((2, 32))
print(my_a1)
print()
# vibo: через resize()
my_a.resize((2, 32))
print(my_a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64]

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
  25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56
  57 58 59 60 61 62 63 64]]

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
  25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56
  57 58 59 60 61 62 63 64]]


##### resize()

In [38]:
a = np.zeros((4, 3), dtype="uint8")
print(a)
print()
a.resize((2, 2, 3))
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


In [91]:
# vibo: свой пример
my_a = np.arange(1, 65, 1)
print(my_a)
print()
# vibo: resize
my_a.resize((2, 3, 16))
print(my_a)
print()
# vibo: reshape автоматически рассчитывает размер
my_a = my_a.reshape(2, -1, 16)
print(my_a)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64]

[[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
  [17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32]
  [33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]]

 [[49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]]

[[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
  [17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32]
  [33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]]

 [[49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]]


In [42]:
# если в reshape() указать значение -1 по одной или нескольким осям, то значения размерности рассчитаются автоматически:

a = np.zeros((4, 3), dtype="uint8")
print(a)
print()
a = a.reshape((2, 3, -1))
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]

[[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]


##### Математические операции

In [92]:
a = np.array([9, 8, 7])
b = np.array([1, 2, 3])
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[10 10 10]
[8 6 4]
[ 9 16 21]
[9.         4.         2.33333333]


In [93]:
# vibo: умножение матриц @ или функция dot
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
b = np.array([[0, 0, 1],
              [0, 1, 0],
              [1, 0, 0]])
print(a @ b)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [94]:
# vibo: транспонировани, поворот матриц
a = np.arange(1, 13).reshape(4, 3)
print(a)
print("Транспонирование")
print(a.transpose())
print("Поворот вправо")
print(np.rot90(a))
print("Поворот влево")
print(np.rot90(a, -1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Транспонирование
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
Поворот вправо
[[ 3  6  9 12]
 [ 2  5  8 11]
 [ 1  4  7 10]]
Поворот влево
[[10  7  4  1]
 [11  8  5  2]
 [12  9  6  3]]


##### Агрегирующие функции

In [95]:
# vibo: по умолчанию размерность не учитывается
a = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])
print(a.sum())
print(a.min())
print(a.max())

45
1
9


In [96]:
# vibo: c указанием осей агрегации
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(a.sum(axis=0))  # сумма чисел в каждом столбце
print(a.sum(axis=1))  # сумма чисел в каждой строке
print(a.min(axis=0))  # минимум по столбцам
print(a.max(axis=1))  # максимум по строкам

[12 15 18]
[ 6 15 24]
[1 2 3]
[3 6 9]


##### Срезы

In [97]:
a = np.arange(1, 13).reshape(3, 4)
print(a)
print()
print(a[:2, 2:])
print()
print(a[:, ::2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[3 4]
 [7 8]]

[[ 1  3]
 [ 5  7]
 [ 9 11]]


##### Проход for по элементам массива

In [99]:
# vibo: проход по элементам первой оси массива
a = np.arange(1, 13).reshape(3, 4)
print(a)
print()
for row in a:
    print(row)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


##### Линеаризация

In [100]:
# vibo: линеаризация массива
a = np.arange(1, 13).reshape(3, 4)
print(a)
print()
print("; ".join(str(el) for el in a.flat))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

1; 2; 3; 4; 5; 6; 7; 8; 9; 10; 11; 12


##### Сравнение скорости работы массива и списка

In [101]:
from time import time

t = time()
print(f"Результат итератора: {sum(x ** 0.5 for x in range(10 ** 7))}.")
print(f"{time() - t} с.")
t = time()
print(f"Результат numpy: {np.sqrt(np.arange(10 ** 7)).sum()}.")
print(f"{time() - t} с.")

Результат итератора: 21081849486.439312.
1.252307653427124 с.
Результат numpy: 21081849486.442448.
0.03884577751159668 с.


### Практика /10

In [109]:
# A ПОЛНОЕ РЕШЕНИЕ
import math


x = float(input())


def f(x):
    return math.log(x ** (3 / 16), 32) + x ** (math.cos((math.pi * x) / (2 * math.e))) - (math.sin(x / math.pi)) ** 2


print(f(x))

4.880549344757598


In [144]:
# B ПОЛНОЕ РЕШЕНИЕ
# vibo: потоковый НОД
from sys import stdin
import math


def f(x):
    return math.gcd(*[int(x) for x in x.split()])


lines = []
for line in stdin:
    lines.append(line.rstrip("\n"))

for string in lines:
    print(f(string))

In [153]:
# C НЕВЕРНОЕ РЕШЕНИЕ
# vibo: WA на тесте-7
# vibo: задача на комбинаторику

# vibo: n -  зрителей на мероприятии
# vibo: m - количество мест
import math


n, m = input().split()


def f(n, m):
    n, m = int(n), int(m)
    # vibo: количество вариантов, в которых участник попадает на семинар
    c1 = (math.factorial(n - 1)) / (math.factorial(m - 1) * math.factorial((n - 1) - (m - 1)))
    # vibo: количество всех вариантов групп на семинаре
    c2 = (math.factorial(n)) / (math.factorial(m) * math.factorial(n - m))
    return int(c1), int(c2)


print(*f(n, m))

# vibo: Пример 1.
# 4 2 -> 3 6

# vibo: Пример 2.
# 10 3 -> 36 120


36 120


In [177]:
# D ПОЛНОЕ РЕШЕНИЕ
# vibo: среднее геометрическое
import math


x = [float(x) for x in input().split()]
n = len(x)


def f(*x):
    return math.prod(*x) ** (1 / n)


print(f(x))

# vibo: Пример 1.
# 1 2 3 4 5 -> 2.605171084697352

# vibo: Пример 2.
# 1.1 1.2 1.3 1.4 1.5 -> 1.292252305460076

1.292252305460076


In [ ]:
# E

In [180]:
# F
import numpy as np


def multiplication_matrix(x):
    return np.arange(1, x ** 2 + 1, 1).reshape(x, x)


# vibo: Пример 1.
print(multiplication_matrix(3))

# # vibo: Пример 2.
# print(multiplication_matrix(5))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
